apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  minReplicas: {{ .Values.app.scale.minReplica }}
  maxReplicas: {{ .Values.app.scale.maxReplicas }}
  targetCPUUtilizationPercentage: 60

