apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.app.appconfig.httpport }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-lbl-service
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.app.appconfig.httpport }}      